#!/bin/bash

# NOTE: make sure to 'source' when running the script
# eg. -> . setJava6

# set java 6
JAVA_HOME=/usr/local/java/jdk1.6.0_45
export JAVA_HOME
JRE_HOME=/usr/local/java/jre1.6.0_45
export JRE_HOME
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
export PATH


# may also have to do this
sudo update-alternatives --set java /usr/local/java/jre1.6.0_45/bin/java
sudo update-alternatives --set javac /usr/local/java/jdk1.6.0_45/bin/javac
sudo update-alternatives --set javaws /usr/local/java/jre1.6.0_45/bin/javaws
